export enum ErrorCode {
  GAME_DEFINITION_NOT_FOUND = 'GAME_DEFINITION_NOT_FOUND',
  GAME_FAMILY_NOT_FOUND = 'GAME_FAMILY_NOT_FOUND',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  GAME_SCOPE_REQUIRED = 'GAME_SCOPE_REQUIRED',
  INVALID_GAME_SCOPE_COMBINATION = 'INVALID_GAME_SCOPE_COMBINATION',
  GAME_DEFINITION_INACTIVE = 'GAME_DEFINITION_INACTIVE',
  GAME_SESSION_NOT_FOUND = 'GAME_SESSION_NOT_FOUND',
  GAME_SESSION_NOT_ACTIVE = 'GAME_SESSION_NOT_ACTIVE',
  PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND',
  PLAYER_NOT_ELIGIBLE = 'PLAYER_NOT_ELIGIBLE',
  PLAYER_ALREADY_SELECTED = 'PLAYER_ALREADY_SELECTED',
  SELECTION_LIMIT_REACHED = 'SELECTION_LIMIT_REACHED',
  NOT_YOUR_TURN = 'NOT_YOUR_TURN',
  INVALID_GAME_ACTION = 'INVALID_GAME_ACTION',
  ACTION_ALREADY_PROCESSED = 'ACTION_ALREADY_PROCESSED',
  STATE_VERSION_CONFLICT = 'STATE_VERSION_CONFLICT',
  METRIC_VALUE_MISSING = 'METRIC_VALUE_MISSING',
  RESULT_NOT_AVAILABLE = 'RESULT_NOT_AVAILABLE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export class DomainException extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly details: Record<string, unknown> = {},
  ) {
    super(message);
    this.name = 'DomainException';
  }
}
