version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: futziq-postgres
    environment:
      POSTGRES_USER: futziq
      POSTGRES_PASSWORD: futziq
      POSTGRES_DB: futziq
    ports:
      - '5432:5432'
    volumes:
      - futziq_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U futziq']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: futziq-redis
    ports:
      - '6379:6379'
    profiles:
      - redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  futziq_pg_data:
